import Mathlib


noncomputable section
namespace s1

-- paper: "Let B = {b₁, . . . , bₙ} ⊂ ℝⁿ consist of n linearly independent vectors."
-- let's see. Mathlib has a definition of Linear Independence:
#reduce LinearIndependent
-- it states that linear combinations of the family v are unique.
-- "A module is a generalization of vector spaces to a scalar semiring."
#check Module
-- in our case, where ℝ is a field and ℝⁿ is an additive group, there is no difference to a vector.
-- paper: "A lattice is a discrete additive subgroup of ℝⁿ."
--   (wait, what does "discrete" mean?)
-- yes, this is expressable in Lean.
#check AddSubgroup

-- let's define ℝⁿ, B and Λ

-- btw, this is how a family v : ι → M is coerced into a basis:
#check Module.Basis.mk


variable {n : ℕ}
-- let's define an element of ℝⁿ as a function from the canonical type with n elements to ℝ
abbrev Rn := Fin n → ℝ
-- using abbrev makes it so lean automatically recognizes it as `Fin n → ℝ`

-- let's show that Rn is a vector space

-- define the additive group of Rn the usual way for functions into an additive group
set_option trace.Meta.synthInstance true in
instance Rn.instAddCommGroup : AddCommGroup (@Rn n) := Pi.addCommGroup
-- we are required to use `(@Rn n)` instead of just `Rn` for reasons
-- -- btw, Pi.addCommGroup can actually even handle functions whose output type depends on the input:
-- #check Pi.addCommGroup

set_option trace.Meta.synthInstance true in -- displays the implicit instances
noncomputable example : Module ℝ (Fin n → ℝ) := Pi.Function.module (Fin n) ℝ ℝ
-- hm? that requires a noncomputable? "depends on `Real.instRCLike`"
-- huh? it uses vvv to instantiate `Module ℝ ℝ`?
#check RCLike.toInnerProductSpaceReal.toModule
#check Real.instRCLike
-- nevermind this, it's not directly compatible with the earlier.
-- noncomputable example : Module ℝ ℝ := inferInstance

-- what did the `AddCommGroup (@Rn n)` use?

-- uh, anyway

-- example (i : Fin n) (x y : Rn) : (x + y) i = x i + y i := by rfl

#check Vector.instAddCommGroup

-- instance : DistribMulAction
-- instance : AddCommMonoid (Vector ℝ n) := by apply?
-- instance : Module ℝ (Vector ℝ n) := inferInstance

set_option trace.Meta.synthInstance true in
example : SMul ℝ (@Rn n) := Function.hasSMul

-- set_option trace.Meta.synthInstance true in
-- example : @Module ℝ (@Rn n) _ (Rn.instAddCommGroup.toAddCommMonoid) where
--   add_smul := sorry
--   zero_smul := sorry

-- wait, there's some issues

set_option trace.Meta.synthInstance true in
instance Rn.instModule : @Module ℝ (@Rn n) Real.instRing.toSemiring (Rn.instAddCommGroup.toAddCommMonoid) := inferInstance

-- I hope that works

variable {B : Fin n → Rn} (hli: LinearIndependent ℝ B)

-- oh yeah, I can just define Λ as the subgroup generated by B
def Λ {B : Fin n → Rn} {_ : LinearIndependent ℝ B} := @AddSubgroup.closure (@Rn n) (Rn.instAddCommGroup.toAddGroup) (Set.range B)
-- lemma Λ.Bc : (Λ hli) = sorry := sorry
-- hm, defining it as the set of Bc?

-- just checking
def test.Λ := @AddSubgroup.closure (@Rn n) _ (Set.range B)
example : @Λ n B hli = @test.Λ n B := rfl

-- vvv is this good practise? I don't recall
instance : AddCommGroup (@Λ n B hli) := Λ.toAddCommGroup

-- instance : NormedAddCommGroup (@Λ n B hli) :=

-- hm, should I      (should I what? what was I going to say?)

-- wait
#check EuclideanSpace
-- I should use this.

end s1


open Module

variable {n : ℕ}
-- let's define an element of ℝⁿ as a function from the canonical type with n elements to ℝ
abbrev Rn := EuclideanSpace ℝ (Fin n)

#check ![1 , 2, (3 : ℤ)]
#check !₂[1 , 2, (3 : ℤ)]
#check !![1 , 2, 3; 4, 5, 6]

-- example : LinearEquiv (@Rn n) (Fin n → ℝ) := by sorry


instance Rn.instAddCommGroup : AddCommGroup (@Rn n) := inferInstance
instance Rn.instAddCommMonoid : AddCommGroup (@Rn n) := instAddCommGroup

instance Rn.instModule : @Module ℝ (@Rn n) Real.instRing.toSemiring (Rn.instAddCommGroup.toAddCommMonoid) := inferInstance

variable {B : Basis (Fin n) ℝ (@Rn n)}

-- wait, where's the theorem that n linearly independent vectors are a basis?

example {B : Fin n → (@Rn n)} (hli: LinearIndependent ℝ B) : ⊤ ≤ Submodule.span ℝ (Set.range B) := sorry

-- example := Module.Basis.mk hli _


def Λ (B : Basis (Fin n) ℝ (@Rn n))
  : AddSubgroup (@Rn n)
  := @AddSubgroup.closure (@Rn n) (Rn.instAddCommGroup.toAddGroup) (Set.range B)


#check fun x ↦ B x

-- abbrev Zn := Fin n → ℤ

abbrev Zn' : Set (Fin n → ℝ) := Set.range ((Int.cast : ℤ → ℝ) ∘ ·)
-- abbrev Zn'' : Set (Fin n →₀ ℝ) := Finsupp.equivFunOnFinite.symm '' Zn'
abbrev Zn₀ : Set (Fin n →₀ ℝ) := Set.range ( Finsupp.equivFunOnFinite.symm <| ((↑) : ℤ → ℝ) ∘ ·)


lemma Λ.BZ : Λ B = B.repr.symm '' Zn₀ := by
  ext x

  simp only [SetLike.mem_coe, Basis.repr_symm_apply, Set.mem_image, Set.mem_range,
    exists_exists_eq_and]
  refine ⟨?_,?_⟩
  rw [Λ,AddSubgroup.mem_closure]
  intro xin

  sorry
  sorry

instance : AddCommGroup (Λ B) := AddSubgroup.toAddCommGroup _

lemma Λ.B_in (i) : B i ∈ Λ B := by
  rw [Λ]
  apply AddSubgroup.mem_closure_of_mem -- aesop
  simp_all only [Set.mem_range, exists_apply_eq_apply]

variable (B) in
def Λ.basis : Fin n → Λ B := fun i ↦ ⟨B i,Λ.B_in i⟩

-- maybe define Module ℤ (Λ B)

example : Basis (Fin n) ℤ (Λ B) := Basis.mk (R := ℤ) (v := Λ.basis B) sorry sorry


-- coercions
example (q : @Rn n) : Fin n → ℝ := q
example (q : Λ B) : (@Rn n) := by
  #check q
  exact q.val

example : Norm ℝ := by exact Real.norm

example : Norm (@Rn n) := by exact PiLp.instNorm 2 fun x ↦ ℝ

open NNReal

def Λ.minimum_distance (norm : Rn → ℝ≥0) := ⨅ (x ∈ (Λ B)) (_ : x ≠ 0), norm x

/-
paper:
The minimum distance λ1(Λ) of a lattice Λ is the length (in the Euclidean `2 norm, unless otherwise
indicated) of its shortest nonzero vector: λ1(Λ) = min06=x∈Λkxk. More generally, the ith successive
minimum λi(Λ) is the smallest radius r such that Λ contains i linearly independent vectors of norm at
most r. We write λ∞
1
to denote the minimum distance measured in the ∞ norm (which is defined as ‖x‖∞ = max |xᵢ|).
-/
-- i or more
def Λ.successive_minimum_distance (norm : (@Rn n) → ℝ≥0) (i : ℕ)
  := ⨅ (r : ℝ≥0) (_ : ∃s ⊆ ((Λ B).carrier), LinearIndependent ℝ (Subtype.val : s → Rn) ∧ s.encard ≤ i ∧ ∀x ∈ s, norm x ≤ r), r
-- note: for i := 0 this is ⊥ and i := 1 this is 0

-- quotient groups

-- example (B' : Basis (Fin n) ℝ (@Rn n)) := (Λ B) ⧸ (Λ B')
-- example (b : @Rn n) := Λ B ⧸ b
-- example (B' : Basis (Fin n) ℝ (@Rn n)) :=
#check QuotientAddGroup.coe_mk'


instance : AddSubgroup.Normal (Λ B) := AddSubgroup.normal_of_comm (Λ B)

-- hmm, hold on, paper: "Therefore for lattices Λ' ⊆ Λ,..."
-- sub-lattices? Oh, these aren't full-rank lattices. confusing
-- wait, we can just use subgroups of Λ, since they are also lattices? is that correct? VERIFY

example (Λ' : AddSubgroup (Λ B)) (a b : (Λ B) ⧸ Λ') : a + b = b + a := by
  exact AddCommMagma.add_comm a b

-- example (Λ' : AddSubgroup (Λ B)) (a : (Λ B) ⧸ Λ') (x) : x ∈ a := sorry


-- what does "full-rank set of lattice vectors" mean?
-- I assume a set whose span is the whole space
-- wait, hold on, what is "the whole space"? Λ or ℝⁿ?

-- is "a basis T of Λ" a `Basis (Fin n) ℤ (Λ B)`

-- def lemma_2_1 (S : Set (Λ B)) (h : ⊤ ≤ Submodule.span ℝ ((Subtype.val) '' S)) : Basis (Fin n) ℤ (Λ B) := sorry

#check Basis.addHaar

-- 1. [https://en.wikipedia.org/wiki/Lattice_(group)]
-- 2. [https://en.wikipedia.org/wiki/Lattice_(module)]
-- 3. [https://en.wikipedia.org/wiki/Lattice_(discrete_subgroup)]
-- I must study to find the best formalism.
--
-- about paper: "A lattice is a discrete additive subgroup of ℝⁿ",
-- "Lattice (discrete subgroup)" links [https://en.wikipedia.org/wiki/Discrete_group], which is [https://en.wikipedia.org/wiki/Topological_group]
#check IsTopologicalAddGroup
#check DiscreteTopology -- Λ has this?
    -- 𝓛 is written \MCL
-- (forgot what I was going to note)
-- "Lattice (group)" states "Every point in the space is within some maximum distance of a lattice point.". this definition means it is full-rank
#check Basis

-- what can be a "discrete additive subgroup"? is that definition enough?
/-
relaxing that it's generated by a basis, or linearly independent vectors
does discreteness imply linear independence? - no.
if v u are linearly dependent, u = r * v where r is real
is the finitely generated (v, r*v) non-discrete?
it's equal to (1,r) * v
it's as discrete as (1,r)
(1, r)
can you find a linear combination of 1 and r that is arbitrarily close to some point?
    take a rational approximation a/b of r.
    1 * a - r * b = a - r * b
  assume 0 < r < 1 (using r := r - ⌊r⌋ * 1)
    a => 1-a
    take the smaller one, unless a = 1/2
  if r = a/b is rational, then x * 1 + y * a/b = (x * b + y * a)/b which can only be as small as 1/b, so it's discrete
-- ah, obviously, it's discrete iff there's only finite elements in [0,1]

-/
#check Set.matrix

#check Matrix.mul_apply

open scoped Matrix

example {m n} [Fintype n] (A : Matrix m n ℝ) (v : n → ℝ) := A *ᵥ v

-- variable {B' : Matrix}

-- let's revise Zn
#check Zn'
abbrev Zn (ι : Type*) : Set (ι → ℝ) := Set.range ((Int.cast : ℤ → ℝ) ∘ ·)
lemma Zn.mem_int {ι : Type*} {x} : (Int.cast : ℤ → ℝ) ∘ x ∈ Zn ι := ⟨x,rfl⟩
lemma Zn.mem_int' {ι : Type*} {x : ι → ℤ} : (Int.cast <| x ·) ∈ Zn ι := ⟨x,rfl⟩

-- should I generalize further? there was ℤₐⁿ

#check Pi.intCast_def

-- def Zn.general (ι : Type*) (R : Type*) [IntCast R] : Set (ι → R) := Set.range ((Int.cast : ℤ → R) ∘ ·)


#check canLift
instance Zn.canLift {ι : Type*} : CanLift (ι → ℝ) (ι → ℤ) (Int.cast <| · ·) fun f => f ∈ Zn ι where
  prf := fun _ a ↦ a

@[simp]
theorem Zn.add {ι : Type*} {x y} (hx : x ∈ Zn ι) (hy : y ∈ Zn ι) : (x + y) ∈ Zn ι := by
  lift x to ι → ℤ using hx
  lift y to ι → ℤ using hy
  rw [Pi.add_def _ _]
  norm_cast
  exact Zn.mem_int'

#check PMF.bind_map


def 𝓛.ofMatrix {ι n} [Fintype n] (B : Matrix ι n ℝ) := (B.mulVec : (n → ℝ) → (ι → ℝ)) '' (Zn n)
--  (⟨B.mulVec,B.mulVec_add⟩ : (n → ℝ) →ₙ+ (ι → ℝ))

-- theorem 𝓛.ofMatrix_def {ι n} [Fintype n] (B : Matrix ι n ℝ) : 𝓛.ofMatrix B = (B.mulVec : (n → ℝ) → (ι → ℝ)) '' (Zn n)

#check Matrix.mulVec_add

def 𝓛.ofMatrix' {ι n} [Fintype n] (B : Matrix ι n ℝ) : AddSubgroup (ι → ℝ) where
  carrier := 𝓛.ofMatrix B
  add_mem'  := by
    unfold ofMatrix at *
    -- simp_all only [Set.mem_image]
    intro Bx By ⟨x,hx,hBx⟩ ⟨y,hy,hBy⟩
    subst hBy hBx
    refine ⟨x + y,Zn.add hx hy,Matrix.mulVec_add _ _ _⟩
  zero_mem' := by
    refine ⟨0,⟨0,?_⟩,?_⟩
    simp only [Pi.comp_zero, Int.cast_zero, Function.const_zero]
    simp only [Matrix.mulVec_zero]

  neg_mem' := by
    intro Bx ⟨x,hx,hBx⟩
    subst hBx
    unfold ofMatrix
    simp only [Set.mem_image, Set.mem_range, exists_exists_eq_and]




    sorry

-- todo: note that the function from (ι → ℤ) is a group homomorphism
#check AddHom
