import Mathlib


noncomputable section
namespace s1

-- paper: "Let B = {b₁, . . . , bₙ} ⊂ ℝⁿ consist of n linearly independent vectors."
-- let's see. Mathlib has a definition of Linear Independence:
#reduce LinearIndependent
-- it states that linear combinations of the family v are unique.
-- "A module is a generalization of vector spaces to a scalar semiring."
#check Module
-- in our case, where ℝ is a field and ℝⁿ is an additive group, there is no difference to a vector.
-- paper: "A lattice is a discrete additive subgroup of ℝⁿ."
--   (wait, what does "discrete" mean?)
-- yes, this is expressable in Lean.
#check AddSubgroup

-- let's define ℝⁿ, B and Λ

-- btw, this is how a family v : ι → M is coerced into a basis:
#check Module.Basis.mk


variable {n : ℕ}
-- let's define an element of ℝⁿ as a function from the canonical type with n elements to ℝ
abbrev Rn := Fin n → ℝ
-- using abbrev makes it so lean automatically recognizes it as `Fin n → ℝ`

-- let's show that Rn is a vector space

-- define the additive group of Rn the usual way for functions into an additive group
set_option trace.Meta.synthInstance true in
instance Rn.instAddCommGroup : AddCommGroup (@Rn n) := Pi.addCommGroup
-- we are required to use `(@Rn n)` instead of just `Rn` for reasons
-- -- btw, Pi.addCommGroup can actually even handle functions whose output type depends on the input:
-- #check Pi.addCommGroup

set_option trace.Meta.synthInstance true in -- displays the implicit instances
noncomputable example : Module ℝ (Fin n → ℝ) := Pi.Function.module (Fin n) ℝ ℝ
-- hm? that requires a noncomputable? "depends on `Real.instRCLike`"
-- huh? it uses vvv to instantiate `Module ℝ ℝ`?
#check RCLike.toInnerProductSpaceReal.toModule
#check Real.instRCLike
-- nevermind this, it's not directly compatible with the earlier.
-- noncomputable example : Module ℝ ℝ := inferInstance

-- what did the `AddCommGroup (@Rn n)` use?

-- uh, anyway

-- example (i : Fin n) (x y : Rn) : (x + y) i = x i + y i := by rfl

#check Vector.instAddCommGroup

-- instance : DistribMulAction
-- instance : AddCommMonoid (Vector ℝ n) := by apply?
-- instance : Module ℝ (Vector ℝ n) := inferInstance

set_option trace.Meta.synthInstance true in
example : SMul ℝ (@Rn n) := Function.hasSMul

-- set_option trace.Meta.synthInstance true in
-- example : @Module ℝ (@Rn n) _ (Rn.instAddCommGroup.toAddCommMonoid) where
--   add_smul := sorry
--   zero_smul := sorry

-- wait, there's some issues

set_option trace.Meta.synthInstance true in
instance Rn.instModule : @Module ℝ (@Rn n) Real.instRing.toSemiring (Rn.instAddCommGroup.toAddCommMonoid) := inferInstance

-- I hope that works

variable {B : Fin n → Rn} (hli: LinearIndependent ℝ B)

-- oh yeah, I can just define Λ as the subgroup generated by B
def Λ {B : Fin n → Rn} {_ : LinearIndependent ℝ B} := @AddSubgroup.closure (@Rn n) (Rn.instAddCommGroup.toAddGroup) (Set.range B)
-- lemma Λ.Bc : (Λ hli) = sorry := sorry
-- hm, defining it as the set of Bc?

-- just checking
def test.Λ := @AddSubgroup.closure (@Rn n) _ (Set.range B)
example : @Λ n B hli = @test.Λ n B := rfl

-- vvv is this good practise? I don't recall
instance : AddCommGroup (@Λ n B hli) := Λ.toAddCommGroup

-- instance : NormedAddCommGroup (@Λ n B hli) :=

-- hm, should I      (should I what? what was I going to say?)

-- wait
#check EuclideanSpace
-- I should use this.

end s1
namespace s2

open Module

variable {n : ℕ}
-- let's define an element of ℝⁿ as a function from the canonical type with n elements to ℝ
abbrev Rn := EuclideanSpace ℝ (Fin n)

#check ![1 , 2, (3 : ℤ)]
#check !₂[1 , 2, (3 : ℤ)]
#check !![1 , 2, 3; 4, 5, 6]

-- example : LinearEquiv (@Rn n) (Fin n → ℝ) := by sorry


instance Rn.instAddCommGroup : AddCommGroup (@Rn n) := inferInstance
instance Rn.instAddCommMonoid : AddCommGroup (@Rn n) := instAddCommGroup

instance Rn.instModule : @Module ℝ (@Rn n) Real.instRing.toSemiring (Rn.instAddCommGroup.toAddCommMonoid) := inferInstance

variable {B : Basis (Fin n) ℝ (@Rn n)}

-- wait, where's the theorem that n linearly independent vectors are a basis?

example {B : Fin n → (@Rn n)} (hli: LinearIndependent ℝ B) : ⊤ ≤ Submodule.span ℝ (Set.range B) := sorry

-- example := Module.Basis.mk hli _


def Λ (B : Basis (Fin n) ℝ (@Rn n))
  : AddSubgroup (@Rn n)
  := @AddSubgroup.closure (@Rn n) (Rn.instAddCommGroup.toAddGroup) (Set.range B)


#check fun x ↦ B x

-- abbrev Zn := Fin n → ℤ

abbrev Zn' : Set (Fin n → ℝ) := Set.range ((Int.cast : ℤ → ℝ) ∘ ·)
-- abbrev Zn'' : Set (Fin n →₀ ℝ) := Finsupp.equivFunOnFinite.symm '' Zn'
abbrev Zn₀ : Set (Fin n →₀ ℝ) := Set.range ( Finsupp.equivFunOnFinite.symm <| ((↑) : ℤ → ℝ) ∘ ·)


lemma Λ.BZ : Λ B = B.repr.symm '' Zn₀ := by
  ext x

  simp only [SetLike.mem_coe, Basis.repr_symm_apply, Set.mem_image, Set.mem_range,
    exists_exists_eq_and]
  refine ⟨?_,?_⟩
  rw [Λ,AddSubgroup.mem_closure]
  intro xin

  sorry
  sorry

instance : AddCommGroup (Λ B) := AddSubgroup.toAddCommGroup _

lemma Λ.B_in (i) : B i ∈ Λ B := by
  rw [Λ]
  apply AddSubgroup.mem_closure_of_mem -- aesop
  simp_all only [Set.mem_range, exists_apply_eq_apply]

variable (B) in
def Λ.basis : Fin n → Λ B := fun i ↦ ⟨B i,Λ.B_in i⟩

-- maybe define Module ℤ (Λ B)

example : Basis (Fin n) ℤ (Λ B) := Basis.mk (R := ℤ) (v := Λ.basis B) sorry sorry


-- coercions
example (q : @Rn n) : Fin n → ℝ := q
example (q : Λ B) : (@Rn n) := by
  #check q
  exact q.val

example : Norm ℝ := by exact Real.norm

example : Norm (@Rn n) := by exact PiLp.instNorm 2 fun x ↦ ℝ

open NNReal

def Λ.minimum_distance (norm : Rn → ℝ≥0) := ⨅ (x ∈ (Λ B)) (_ : x ≠ 0), norm x

/-
paper:
The minimum distance λ1(Λ) of a lattice Λ is the length (in the Euclidean `2 norm, unless otherwise
indicated) of its shortest nonzero vector: λ1(Λ) = min06=x∈Λkxk. More generally, the ith successive
minimum λi(Λ) is the smallest radius r such that Λ contains i linearly independent vectors of norm at
most r. We write λ∞
1
to denote the minimum distance measured in the ∞ norm (which is defined as ‖x‖∞ = max |xᵢ|).
-/
-- i or more
def Λ.successive_minimum_distance (norm : (@Rn n) → ℝ≥0) (i : ℕ)
  := ⨅ (r : ℝ≥0) (_ : ∃s ⊆ ((Λ B).carrier), LinearIndependent ℝ (Subtype.val : s → Rn) ∧ s.encard ≤ i ∧ ∀x ∈ s, norm x ≤ r), r
-- note: for i := 0 this is ⊥ and i := 1 this is 0

-- quotient groups

-- example (B' : Basis (Fin n) ℝ (@Rn n)) := (Λ B) ⧸ (Λ B')
-- example (b : @Rn n) := Λ B ⧸ b
-- example (B' : Basis (Fin n) ℝ (@Rn n)) :=
#check QuotientAddGroup.coe_mk'


instance : AddSubgroup.Normal (Λ B) := AddSubgroup.normal_of_comm (Λ B)

-- hmm, hold on, paper: "Therefore for lattices Λ' ⊆ Λ,..."
-- sub-lattices? Oh, these aren't full-rank lattices. confusing
-- wait, we can just use subgroups of Λ, since they are also lattices? is that correct? VERIFY

example (Λ' : AddSubgroup (Λ B)) (a b : (Λ B) ⧸ Λ') : a + b = b + a := by
  exact AddCommMagma.add_comm a b

-- example (Λ' : AddSubgroup (Λ B)) (a : (Λ B) ⧸ Λ') (x) : x ∈ a := sorry


-- what does "full-rank set of lattice vectors" mean?
-- I assume a set whose span is the whole space
-- wait, hold on, what is "the whole space"? Λ or ℝⁿ?

-- is "a basis T of Λ" a `Basis (Fin n) ℤ (Λ B)`

-- def lemma_2_1 (S : Set (Λ B)) (h : ⊤ ≤ Submodule.span ℝ ((Subtype.val) '' S)) : Basis (Fin n) ℤ (Λ B) := sorry

#check Basis.addHaar

-- 1. [https://en.wikipedia.org/wiki/Lattice_(group)]
-- 2. [https://en.wikipedia.org/wiki/Lattice_(module)]
-- 3. [https://en.wikipedia.org/wiki/Lattice_(discrete_subgroup)]
-- I must study to find the best formalism.
--
-- about paper: "A lattice is a discrete additive subgroup of ℝⁿ",
-- "Lattice (discrete subgroup)" links [https://en.wikipedia.org/wiki/Discrete_group], which is [https://en.wikipedia.org/wiki/Topological_group]
#check IsTopologicalAddGroup
#check DiscreteTopology -- Λ has this?
    -- 𝓛 is written \MCL
-- (forgot what I was going to note)
-- "Lattice (group)" states "Every point in the space is within some maximum distance of a lattice point.". this definition means it is full-rank
#check Basis

-- what can be a "discrete additive subgroup"? is that definition enough?
/-
relaxing that it's generated by a basis, or linearly independent vectors
does discreteness imply linear independence? - no.
if v u are linearly dependent, u = r * v where r is real
is the finitely generated (v, r*v) non-discrete?
it's equal to (1,r) * v
it's as discrete as (1,r)
(1, r)
can you find a linear combination of 1 and r that is arbitrarily close to some point?
    take a rational approximation a/b of r.
    1 * a - r * b = a - r * b
  assume 0 < r < 1 (using r := r - ⌊r⌋ * 1)
    a => 1-a
    take the smaller one, unless a = 1/2
  if r = a/b is rational, then x * 1 + y * a/b = (x * b + y * a)/b which can only be as small as 1/b, so it's discrete
-- ah, obviously, it's discrete iff there's only finite elements in [0,1]

-/
#check Set.matrix

#check Matrix.mul_apply

open scoped Matrix

example {m n} [Fintype n] (A : Matrix m n ℝ) (v : n → ℝ) := A *ᵥ v

variable  {ι n : Type*} [Fintype n] (B : Matrix ι n ℝ)
-- todo: should I assume [Fintype ι]? it's going to be true, and a lot relies on it

#check Pi.addMonoidHom
#check Pi.map

#check Pi.instAdd

instance Pi.instAddZero {ι : Type*} {M : ι → Type*}  [(i : ι) → AddZero (M i)] : AddZero (∀ i, M i) := {}

-- def Pi_map_addMonoidHom {ι : Type*} {X Y : ι → Type*}  [(i : ι) → AddZero (X i)] [(i : ι) → AddZero (Y i)] (c : (i : ι) → X i →+ Y i) : ((i : ι) → X i) →+ ((i : ι) → Y i) where
--   toFun := Pi.map (c · ·)
--   map_zero' := by
--     ext x : 1
--     simp_all only [Pi.map_apply, Pi.zero_apply, map_zero]
--   map_add' := by
--     intro x y
--     ext x_1 : 1
--     simp_all only [Pi.map_apply, Pi.add_apply, map_add]


def int_cast : (ι → ℤ) →+ (ι → ℝ) := (Int.castAddHom ℝ).compLeft ι

-- def int_cast : (ι → ℤ) →+ (ι → ℝ) where
--   toFun := (Int.cast <| · ·)
--   map_zero' := funext fun _ ↦ Int.cast_zero
--   map_add' := fun x y ↦ funext fun z ↦ Int.cast_add (x z) (y z)

@[simp]
theorem int_cast.apply (f : ι → ℤ) : int_cast f = (Int.cast <| f ·) := rfl

@[simp high]
theorem int_cast.apply_single [DecidableEq ι] (i : ι) (x) : int_cast (Pi.single i x) = Pi.single i (Int.cast x) := by
  simp
  ext j
  simp only [Pi.single_apply, Int.cast_ite, Int.cast_zero]

example (a : ℤ →+ ℝ) : ℤ →ₗ[ℤ] ℝ := by exact a.toIntLinearMap
#check AddMonoidHom.toIntLinearMap

#check (1 : Matrix ℤ ℤ ℝ)
-- def int_axes (ι : Type*) : Basis ι ℤ (ι → ℤ) where repr := LinearEquiv.refl
-- def int_axes (ι : Type*) [DecidableEq ι] := Set.range (1 : Matrix ι ι ℤ).col
def int_axes (ι : Type*) [Fintype ι] [DecidableEq ι] : Set (ι → ℤ) := Set.range (Pi.single · 1)

-- lemma int_axes.decomposition [Fintype ι] [DecidableEq ι] : int_axes ι

-- #check AddSubgroup.mem_closure_range_iff_of_fintype
theorem int_axes.basis [Fintype ι]  [DecidableEq ι] : AddSubgroup.closure (int_axes ι) = ⊤ := by
  ext x
  simp only [AddSubgroup.mem_top, iff_true]
  apply AddSubgroup.mem_closure_range_iff_of_fintype.mpr
  use x
  exact pi_eq_sum_univ' x


-- variable {B' : Matrix}

-- let's revise Zn

def Zn (ι : Type*) : AddSubgroup (ι → ℝ) := int_cast.range

def Zn.axes (ι : Type*) [Fintype ι] [DecidableEq ι] : Set (ι → ℝ) := int_cast '' (int_axes ι)

theorem Zn.axes_basis [Fintype ι] [DecidableEq ι] : AddSubgroup.closure (Zn.axes ι) = Zn ι := by
  unfold axes Zn
  rw [AddMonoidHom.range_eq_map,←int_axes.basis]
  exact Eq.symm (AddMonoidHom.map_closure int_cast (int_axes ι))


-- should I generalize further? there was ℤₐⁿ

#check Pi.intCast_def

-- def Zn.general (ι : Type*) (R : Type*) [IntCast R] : Set (ι → R) := Set.range ((Int.cast : ℤ → R) ∘ ·)





#check PMF.bind_map



def 𝓛.ofMatrix (B : Matrix ι n ℝ) :=  (Zn n).map (B.mulVecLin : (n → ℝ) →+ (ι → ℝ))


#check B.mulVecLin


theorem 𝓛.ofMatrix_def (B : Matrix ι n ℝ)
  -- : 𝓛.ofMatrix B = (B.mulVec) '' (Set.range ((Int.cast <| · ·) : (_ → _) → _)) := rfl
  -- : 𝓛.ofMatrix B = Set.range (B.mulVec <| ((Int.cast <| · ·) : (_ → _) → _) ·) := by
  : 𝓛.ofMatrix B = Set.range (fun x : _ → _ ↦ B.mulVec (Int.cast <| x ·) ) := by
    sorry

theorem 𝓛.ofMatrix_def_comp (B : Matrix ι n ℝ)
  : 𝓛.ofMatrix B = ( (B.mulVecLin.toAddMonoidHom).comp (int_cast) ).range := by
    sorry

theorem Zn.is_ofMatrix  [Fintype ι] [DecidableEq ι]  : Zn ι = 𝓛.ofMatrix (1 : Matrix ι ι _) := by
  ext x
  simp only [𝓛.ofMatrix, Matrix.mulVecLin_one, AddSubgroup.mem_map, AddMonoidHom.coe_coe,
    LinearMap.id_coe, id_eq, exists_eq_right]




#check Matrix.mulVec_add

-- todo: note that the function from (ι → ℤ) is a group homomorphism
#check AddMonoidHom

#check Matrix.mulVec.addMonoidHomLeft
#check Matrix.ext_addMonoidHom
-- #check Matrix.addMonoidHom
-- wait I'm an idiot, a matrix as a linear map is Matrix.mulVecLin, I found that already

lemma 𝓛.ofMatrix_is_closure (B : Matrix ι n ℝ) : ofMatrix B = AddSubgroup.closure (Set.range B.col) := by
  symm
  apply AddSubgroup.closure_eq_of_le
  ·
    simp [ofMatrix_def_comp]


    intro x ⟨xn,xcol⟩
    subst xcol
    simp only [Set.mem_range, Function.comp_apply, Matrix.mulVecBilin_apply]

    open scoped Classical in
    use Pi.single xn 1
    simp only [int_cast.apply_single, Int.cast_one, Matrix.mulVec_single, MulOpposite.op_one,
      one_smul]
  simp [ofMatrix]



  sorry

-- theorem 𝓛.ofMatrix_def {ι n} [Fintype n] (B : Matrix ι n ℝ) : 𝓛.ofMatrix B = (B.mulVec : (n → ℝ) → (ι → ℝ)) '' (Zn n)

#check Matrix.mulVec_add


-- todo: note that the function from (ι → ℤ) is a group homomorphism
#check AddHom

#check Basis
#check Submodule
#check Submodule.traceDual
-- #check Submodule.traceDual
#check Algebra
-- #check Matrix.mulVec
example : Algebra ℤ ℝ := by exact Ring.toIntAlgebra ℝ
#check IsScalarTower
#check Polynomial

#check dotProductEquiv
#check Dual -- not the same as dual lattice

open Function

-- def 𝓛.dualLattice {ι : Type*} [Fintype ι] (Λ : Set (ι → ℝ)) := { x : ι → ℝ | ∀ v ∈ Λ, dotProduct x v ∈ Set.range (Int.cast)}
#check neg_involutive
#check Function.Involutive


#check AddSubgroup.map -- use to define 𝓛.ofMatrix

-- #check Real
#check Dual

-- theorem 𝓛.dualLattice_basis  {ι n : Type*} [Fintype ι] [Fintype n] (B : Matrix ι n ℝ)
--   : 𝓛.dualLattice (𝓛.ofMatrix B) = { x : ι → ℝ | ∀ v ∈ Set.range (B.col), dotProduct x v ∈ Set.range (Int.cast)} := by
--   sorry

-- wait, sublattices are still n-dimensional? see Corollary 2.8
-- ah, I see. for example 2*Λ is a sublattice of Λ, but Λ with a basis vector removed is not
-- no, nevermind. MG02 defines

#check HomogeneousSubmodule
#check HomogeneousIdeal
#check DirectSum
#check DirectSum.Decomposition
#check Algebra
#check Submodule.IsOrtho
#check Submodule.orthogonal
-- ^^^ would be a subset of a lattice, but it needs [RCLike 𝕜]
#check Orthonormal
#check GradedRing

#check TopologicalSpace
def 𝓛.IsLattice (Λ : AddSubgroup (ι → ℝ)) : Prop := sorry


def 𝓛.dualLattice_general {ι : Type*} [Fintype ι] (S : AddSubgroup ℝ) (Λ : AddSubgroup (ι → ℝ))  : AddSubgroup (ι → ℝ) where
  carrier := { x : ι → ℝ | ∀ v ∈ Λ, x ⬝ᵥ v ∈ S}
  add_mem' := by
    intro a b ha hb v hL
    specialize ha v hL
    specialize hb v hL
    rw [add_dotProduct]
    exact AddMemClass.add_mem ha hb
  zero_mem' := by
    simp only [Set.mem_setOf_eq, zero_dotProduct, zero_mem, implies_true]
  neg_mem' := by
    simp only [Set.mem_setOf_eq, neg_dotProduct, neg_mem_iff, imp_self, implies_true]



def 𝓛.dualLattice {ι : Type*} [Fintype ι] (Λ : AddSubgroup (ι → ℝ)) : AddSubgroup (ι → ℝ) := dualLattice_general (Int.castAddHom ℝ |>.range) Λ


#check Basis.addHaar


theorem 𝓛.dualLattice_involutive  {ι : Type*} [Fintype ι] (S : AddSubgroup ℝ) : Involutive (𝓛.dualLattice_general (ι := ι) S) := by
  -- unfold Involutive
  intro Λ

  -- let p (r : ℝ) := (r ∈ S)
  -- let h (v u : ι → ℝ) := p (v ⬝ᵥ u)


  set Λ' := dualLattice_general S Λ with back

  ext x
  rw [AddSubgroup.ext_iff] at back

  unfold dualLattice_general at back ⊢
  change (∀ v ∈ Λ', x ⬝ᵥ v ∈ S) ↔ x ∈ Λ
  change ∀v, v ∈ Λ' ↔ ∀ x ∈ Λ, v ⬝ᵥ x ∈ S at back
  simp_rw [dotProduct_comm x _]
  refine ⟨?_,fun xL v vL' ↦ (back v).mp vL' x xL⟩

  intro fo

  have : ∀v, v ∈ Λ' → ∀ x ∈ Λ, v ⬝ᵥ x ∈ S := by exact fun v a x a_1 ↦ a x a_1
  have t2: ∀v, (∀ x ∈ Λ, v ⬝ᵥ x ∈ S) → v ∈ Λ' := by exact fun v a ↦ this v (this v (this v (this v a)))

  --  `∀ x ∈ Λ, v ⬝ᵥ x ∈ S` means the preimage of (v ⬝ᵥ) over S contains Λ
  -- or that the image over Λ is in S
  #check AddMonoidHom.range

  let qq (x : ι → ℝ) := (dotProductBilin ℤ ℤ x).toAddMonoidHom

  have nne (v : ι → ℝ): (∀ x ∈ Λ, v ⬝ᵥ x ∈ S) ↔ Λ.map (qq v) ≤ S := by
    simp [qq]
    constructor
    intro eer
    exact AddSubgroup.map_le_iff_le_comap.mpr (this v (this v (this v (this v eer))))
    intro xee x xL
    rw [AddSubgroup.map_le_iff_le_comap] at xee
    simp_all only [implies_true, Λ']
    apply xee
    simp_all only
  simp_all only [implies_true]

  sorry

--

example {ι : Type*} [Fintype ι] (S : AddSubgroup ℝ) (Λ_basis : Set (ι → ℝ))
  : { x : ι → ℝ | ∀ v ∈ AddSubgroup.closure (Λ_basis), x ⬝ᵥ v ∈ S}
  = { x : ι → ℝ | ∀ v ∈ (Λ_basis), x ⬝ᵥ v ∈ S}
  := by
  ext x
  simp only [Set.mem_setOf_eq]

  sorry

-- try dual lattice as a comap

#check dotProductBilin
#check dotProductBilin_apply_apply
#check AddSubgroup.comap
#check dotProductBilin ℤ ℤ

example {ι : Type*} [Fintype ι] (S : AddSubgroup ℝ) (v : ι → ℝ)
  : {x | v ⬝ᵥ x ∈ S} = (v ⬝ᵥ ·) ⁻¹' S
  := by rfl
example {ι : Type*} [Fintype ι] (S : AddSubgroup ℝ) (v : ι → ℝ)
  : {x | v ⬝ᵥ x ∈ S} = (S.comap (dotProductBilin ℤ ℤ v)).carrier
  := by rfl

example {ι : Type*} [Fintype ι] (S : AddSubgroup ℝ) (Λ_basis : Set (ι → ℝ))
  : { x : ι → ℝ | ∀ v ∈ (Λ_basis), v ⬝ᵥ x ∈ S}
  = ⨅ v ∈ Λ_basis, (S.comap (dotProductBilin ℤ ℤ v)).carrier
  := by
    ext x
    simp only [Set.mem_setOf_eq, Set.iInf_eq_iInter, Set.mem_iInter, AddSubsemigroup.mem_carrier,
      AddSubmonoid.mem_toSubsemigroup, AddSubgroup.mem_toAddSubmonoid, AddSubgroup.mem_comap,
      AddMonoidHom.coe_coe, dotProductBilin_apply_apply]


example {ι : Type*} [Fintype ι] (S : AddSubgroup ℝ) (Λ_basis : Finset (ι → ℝ))
  : ⨅ v ∈ Λ_basis, ((S.comap (dotProductBilin ℤ ℤ v)) : AddSubgroup (ι → ℝ)).carrier
  = (⨅ v ∈ Λ_basis, S.comap (dotProductBilin ℤ ℤ v)).carrier
  := by
    ext x
    simp only [Set.iInf_eq_iInter, Set.mem_iInter, AddSubsemigroup.mem_carrier,
      AddSubmonoid.mem_toSubsemigroup, AddSubgroup.mem_toAddSubmonoid, AddSubgroup.mem_comap,
      AddMonoidHom.coe_coe, dotProductBilin_apply_apply]
    constructor
    intro xw ew ⟨G,er⟩
    simp_all
    subst er
    simp only [Set.mem_iInter, SetLike.mem_coe]
    intro y eg
    sorry
    sorry

example [Fintype ι]  (S : AddSubgroup ℝ)
  : { x : ι → ℝ | ∀ v ∈ 𝓛.ofMatrix B, v ⬝ᵥ x ∈ S}
  = { x : ι → ℝ | ∀ z ∈ (Zn n), ((B.mulVecLin : (n → ℝ) →+ (ι → ℝ)) z) ⬝ᵥ x ∈ S}
  := by
    unfold 𝓛.ofMatrix
    simp only [AddSubgroup.mem_map, AddMonoidHom.coe_coe, Matrix.mulVecBilin_apply,
      forall_exists_index, and_imp, forall_apply_eq_imp_iff₂]


example [Fintype ι]  (S : AddSubgroup ℝ)
  : { x : ι → ℝ | ∀ v ∈ 𝓛.ofMatrix B, v ⬝ᵥ x ∈ S}
  = { x : ι → ℝ | ∀ z ∈ (Zn n), dotProductBilin ℤ ℤ ((B.mulVecLin) z) x ∈ S}
  := by
    calc
      {x | ∀ v ∈ 𝓛.ofMatrix B, v ⬝ᵥ x ∈ S} = {x | ∀ z ∈ Zn n, ((dotProductBilin ℤ ℤ) (B.mulVecLin z)) x ∈ S} := sorry
      _ = {x | ∀ z ∈ Zn n, ((dotProductBilin ℤ ℤ) (B.mulVecLin z)) x ∈ S} := by rfl
      _ = {x | ∀ z ∈ Zn n, ((dotProductBilin ℤ ℤ).toAddMonoidHom.comp (B.mulVecLin)) z x ∈ S} := sorry
      _ = {x | ∀ z ∈ Zn n, ((dotProductBilin ℤ ℤ) (B.mulVecLin z)) x ∈ S} := sorry

-- right, if all the basis vectors dotprod to ℤ then the matrix muls to ℤⁿ

open ProbabilityTheory
open MeasureTheory

#check ProbabilityTheory.IsGaussian
#check ProbabilityTheory.gaussianReal
#check ProbabilityTheory.gaussianPDF


def gaussian [Norm (ι → ℝ)] (c : ι → ℝ) (s : ℝ≥0) (x : ι → ℝ) := ProbabilityTheory.gaussianPDF 0 s ‖x - c‖


#check ProbabilityTheory.IsGaussian
#check ProbabilityTheory.isGaussian_map

#check ProbabilityTheory.gaussianReal
#check ProbabilityTheory.gaussianReal _ _ |>.map

#check MeasureTheory.Measure.comap
#check MeasureTheory.Measure.comap_apply

-- we have a function Rn → ℝ, and a measure on ℝ

example [Norm (ι → ℝ)] (c : ι → ℝ) (s : ℝ≥0) : gaussian c s = ProbabilityTheory.gaussianPDF 0 s ∘ (‖· - c‖) := by rfl

#check ProbabilityTheory.gaussianReal
#check MeasureTheory.Measure.withDensity
#check MeasureTheory.Measure.compProd_withDensity
-- look for theorems on this
#check MeasureTheory.pdf_def


#check MeasureTheory.withDensity_pdf_le_map

#check MeasureTheory.pdf

-- nope
example [Norm (ι → ℝ)] (c : ι → ℝ) (s : ℝ≥0) := (ProbabilityTheory.gaussianReal 0 s).comap (‖· - c‖) -- nope, not injective.

#check MeasureTheory.pdf



def gaussianMeasure [Fintype ι] [Norm (ι → ℝ)] (c : ι → ℝ) (s : ℝ≥0) := volume.withDensity (gaussianPDF 0 s ∘ (‖· - c‖))
def gaussianMeasure' [Fintype ι] [Norm (ι → ℝ)] (Λ : AddSubgroup (ι → ℝ)) (c : ι → ℝ) (s : ℝ≥0) := gaussianMeasure c s |>.restrict Λ

def gaussianMeasure'' [Fintype ι] [Norm (ι → ℝ)] (Λ : AddSubgroup (ι → ℝ))  (c : ι → ℝ) (s : ℝ≥0)
  := (gaussianMeasure' Λ c s Set.univ)⁻¹ • (gaussianMeasure' Λ c s)


-- is this true?
-- example  [Fintype ι] [Norm (ι → ℝ)] (c : ι → ℝ) (s : ℝ≥0) : IsGaussian (gaussianMeasure'' c s) := by sorry

#check IsGaussian.toIsProbabilityMeasure

#check IsGaussian.map_eq_gaussianReal



--oh, I found a lattice definition
#check IsZLattice

end s2

namespace s3

open scoped NNReal ENNReal


#check IsZLattice
#check Submodule.IsLattice

abbrev Basis (ι : Type*) [Fintype ι] := Module.Basis ι ℝ (ι → ℝ)

variable {ι : Type*} [Fintype ι] (B : Basis ι)
variable (Λ : Submodule ℤ (ι → ℝ)) [DiscreteTopology Λ] [IsZLattice ℝ Λ]

section lattices

abbrev 𝓛 := Submodule.span ℤ (Set.range B)

-- example :=

example : DiscreteTopology (𝓛 B) := ZSpan.instDiscreteTopologySubtypeMemSubmoduleIntSpanRangeCoeBasisRealOfFinite B
example : IsZLattice ℝ (𝓛 B) := by infer_instance
example : Basis ι := (IsZLattice.basis Λ).ofZLatticeBasis ℝ

def dualLattice_basic : AddSubgroup (ι → ℝ) where
  carrier := { x : ι → ℝ | ∀ v ∈ Λ, x ⬝ᵥ v ∈ (Int.castAddHom ℝ |>.range)}
  add_mem' := by
    intro a b ha hb v hL
    specialize ha v hL
    specialize hb v hL
    rw [add_dotProduct]
    exact AddMemClass.add_mem ha hb
  zero_mem' := by
    simp only [Set.mem_setOf_eq, zero_dotProduct, zero_mem, implies_true]
  neg_mem' := by
    simp only [Set.mem_setOf_eq, neg_dotProduct, neg_mem_iff, imp_self, implies_true]

def dualLattice : Submodule ℤ (ι → ℝ) := (dualLattice_basic Λ).toIntSubmodule

theorem dualLattice.involution : Function.Involutive (dualLattice (ι := ι)) := sorry

-- #check ZSpan

def minimum_distance [Norm (ι → ℝ)] := ⨅ (x ∈ Λ) (_ : x ≠ 0), ‖x‖

/-
paper:
The minimum distance λ1(Λ) of a lattice Λ is the length (in the Euclidean `2 norm, unless otherwise
indicated) of its shortest nonzero vector: λ1(Λ) = min06=x∈Λkxk. More generally, the ith successive
minimum λi(Λ) is the smallest radius r such that Λ contains i linearly independent vectors of norm at
most r. We write λ∞
1
to denote the minimum distance measured in the ∞ norm (which is defined as ‖x‖∞ = max |xᵢ|).
-/
-- i or more
def successive_minimum_distance [Norm (ι → ℝ)] (i : ℕ)
  := ⨅ (r : ℝ≥0) (_ : ∃s ⊆ (Λ.carrier), LinearIndependent ℝ (Subtype.val : s → _) ∧ s.encard ≤ i ∧ ∀x ∈ s, ‖x‖ ≤ r), r
-- note: for i := 0 this is ⊥ and i := 1 this is 0
def successive_minimum_distance' [Norm (ι → ℝ)] (i : ℕ)
  := ⨅ (s ⊆ (Λ.carrier)) (_ : LinearIndependent ℝ (Subtype.val : s → _)) (_ : s.encard ≤ i), ⨆x ∈ s, ‖x‖

-- def dualLattice

end lattices

section gaussians

open ProbabilityTheory
open MeasureTheory


def gaussianFunction [Norm (ι → ℝ)] {s : ℝ≥0} (_ : s ≠ 0) (c : ι → ℝ)  := gaussianPDF 0 s ∘ (‖· - c‖)

#check MeasureTheory.Measure.count
-- #check Measure.comap

#check gaussianReal
/-
2.4 Gaussians on Lattices
ρ s c
-/
def gaussianMeasure [Norm (ι → ℝ)] {s : ℝ≥0} (hs : s ≠ 0)  (c : ι → ℝ) := Measure.count.withDensity (gaussianFunction hs c)

#check ProbabilityMeasure


def gaussianMeasure' [Norm (ι → ℝ)] {s : ℝ≥0} (hs : s ≠ 0) (c : ι → ℝ)  := (gaussianMeasure hs c).restrict Λ


lemma gaussianMeasure'_finite [Norm (ι → ℝ)]  {s : ℝ≥0} (hs : s ≠ 0)  (c : ι → ℝ) : IsFiniteMeasure (gaussianMeasure' Λ hs c) := sorry
-- def gaussianMeasure'_total [Norm (ι → ℝ)] (c : ι → ℝ) {s : ℝ≥0} (hs : s ≠ 0) := (gaussianMeasure' Λ c hs) Set.univ

-- def gaussianDistribution [Norm (ι → ℝ)] {s : ℝ≥0} (hs : s ≠ 0)  (c : ι → ℝ) := ((gaussianMeasure' Λ hs c) Set.univ)⁻¹ • gaussianMeasure' Λ hs c
def gaussianDistribution [Norm (ι → ℝ)] {s : ℝ≥0} (hs : s ≠ 0)  (c : ι → ℝ) := (gaussianMeasure' Λ hs c)[|Set.univ]

lemma gaussianDistribution_prob [Norm (ι → ℝ)] {s : ℝ≥0} (hs : s ≠ 0) (c : ι → ℝ) : IsProbabilityMeasure (gaussianDistribution Λ hs c) := by
  unfold gaussianDistribution
  -- refine cond_isProbabilityMeasure ?_
  refine isProbabilityMeasure_iff.mpr ?_
  simp only [ProbabilityTheory.cond, Measure.restrict_univ, Measure.smul_apply, smul_eq_mul]
  refine ENNReal.inv_mul_cancel ?_ ?_
  -- todo: make its own theorem
  simp only [ne_eq, Measure.measure_univ_eq_zero]
  intro gm
  rw [Measure.ext_iff] at gm
  specialize gm {0}
  simp only [MeasurableSet.singleton, Measure.coe_zero, Pi.ofNat_apply, forall_const] at gm
  unfold gaussianMeasure' gaussianMeasure at gm
  have : {0} ∩ (Λ : Set (ι → ℝ)) = {0} := by
    rw [Set.inter_eq_left, Set.singleton_subset_iff, SetLike.mem_coe]
    exact zero_mem Λ

  simp only [MeasurableSet.singleton, Measure.restrict_apply, this, withDensity_apply,
    Measure.restrict_singleton, Measure.count_singleton', one_smul, lintegral_dirac] at gm
  unfold gaussianFunction gaussianPDF at gm
  simp at gm
  revert gm
  simp only [imp_false, not_le]
  exact gaussianPDFReal_pos _ _ _ hs

  have := gaussianMeasure'_finite Λ hs c
  exact this.1.ne


lemma gaussianDistribution.eq [Norm (ι → ℝ)] {s : ℝ≥0} (hs : s ≠ 0)  (c : ι → ℝ)
  : gaussianDistribution Λ hs c = (gaussianMeasure hs c)[|Λ] := by
    unfold gaussianDistribution gaussianMeasure'
    simp only [ProbabilityTheory.cond, MeasurableSet.univ, Measure.restrict_apply, Set.univ_inter,
      Measure.restrict_univ]


def int_gaussian_real_measure (m) [Norm (Fin m → ℝ)] {s : ℝ≥0} (hs : s ≠ 0)  : Measure (Fin m → ℝ)
  :=
  gaussianDistribution (AddSubgroup.toIntSubmodule (s2.Zn (Fin m))) hs 0



-- def int_gaussian_int_measure (m) [Norm (Fin m → ℝ)] {s : ℝ≥0} (hs : s ≠ 0)  : Measure (Fin m → ℤ)
--   :=  (gaussianMeasure hs 0)[| (s2.Zn (Fin m))].comap ((↑) ∘ ·)
def int_gaussian_int_measure (m) [Norm (Fin m → ℝ)] {s : ℝ≥0} (hs : s ≠ 0) (c : Fin m → ℝ)  : Measure (Fin m → ℤ)
  :=  ((gaussianMeasure hs c).comap ((Int.cast : ℤ → ℝ) ∘ ·))[|Set.univ]

/-- D_{Zᵐ,s} -/
def int_gaussian  (m) [Norm (Fin m → ℝ)] {s : ℝ≥0} (hs : s ≠ 0)  : ProbabilityMeasure (Fin m → ℤ) :=
  ⟨
    int_gaussian_int_measure m hs 0
    , sorry
  ⟩

def int_gaussian_sublattice  (m) [Norm (Fin m → ℝ)] {s : ℝ≥0} (hs : s ≠ 0) (Λ : AddSubgroup (Fin m → ℤ)) (c : Fin m → ℤ) : ProbabilityMeasure (Fin m → ℤ) :=
  ⟨
    (int_gaussian_int_measure m hs ((↑) ∘ c))[|Λ]
    , sorry
  ⟩


end gaussians

/--
η
-/
def smoothing_parameter {ε : ℝ≥0} (_ : ε ≠ 0)
  := ⨅ (s : ℝ≥0) (hs : s ≠ 0) (_ : (gaussianMeasure' (dualLattice Λ) (show s⁻¹ ≠ 0 by simp only [ne_eq,
    inv_eq_zero, hs, not_false_eq_true]) 0) (Set.compl {0}) ≤ ε), s

def infinity_norm : Norm (ι → ℝ) := Pi.normedAddGroup.toNorm

-- justifies changing infinity_norm
example {ι} [Fintype ι] : (⟨fun x ↦ (PiLp.instNorm ∞ (fun (_ : ι) ↦ ℝ)).norm (WithLp.toLp ∞ x)⟩ : Norm (ι → ℝ)) = Pi.normedAddGroup.toNorm := by
  simp only [PiLp.norm_toLp]

/-- λ₁∞ -/
def minimum_distance_sup  := @minimum_distance ι Λ (infinity_norm)

-- what log base?
theorem Lemma_2_6 {ε : ℝ≥0} (he : ε ≠ 0)
  : smoothing_parameter Λ he ≤
  √ (Real.log (2 * Fintype.card ι / (1 + ε⁻¹)) / Real.pi)
  / minimum_distance_sup Λ := sorry

#check EuclideanSpace

-- todo: Norm is just a notation class. theorems about defs using it need [NormedAddCommGroup]
#check NormedAddCommGroup

#check ForIn

#check Monad

def SampleD {n : ℕ} {m : ℕ} (hn : 0 < n) (gs_b : Basis (Fin n)) (s : ℝ≥0) (hs : s ≠ 0) (center : (Fin n) → ℝ) (DZ : {s' : ℝ // s' > 0} → ℝ → PMF (ℤ)) : PMF ( Fin n → ℝ)  := do {
  let mut v : ((Fin n) → ℝ)  := 0;
  let mut c : ((Fin n) → ℝ) := center;

  for hi : i in (Vector.range n).reverse do
    let fi : Fin n := ⟨i,(Vector.mem_range.mp (Vector.mem_reverse.mp hi))⟩
    let bi := gs_b fi
    let c'i : ℝ := (c ⬝ᵥ bi) / (bi ⬝ᵥ bi);
    let s'i : ℝ := s / ‖bi‖;
    have : s'i > 0 := by sorry;
    -- step (b)
    let zi ← (DZ ⟨s'i,this⟩ c'i);
    -- step (c)
    c := (c - zi • bi)
    v := (v + zi • bi)

  return v
}

#check Asymptotics.IsLittleO
open Asymptotics MeasureTheory
open ProbabilityTheory
#check ℙ

-- f(x) = ω(g(x))
notation:100 f " =ω[" l "] " g:100 => g =o[l] f

def negligible {R : Type*} [Norm R] (f : ℕ → R) := ∀(c : ℕ), c > 0 → f =o[Filter.atTop] (fun (n : ℕ) ↦ (n : ℝ) ^ (-(c : ℝ)))

-- #check ProbabilityTheory.HasPDF
#check MeasureTheory.pdf

--- [https://www.cs.bu.edu/~reyzin/teaching/s11cs937/notes-leo-1.pdf]


#check PMF


#check MeasureTheory.SignedMeasure.totalVariation -- Gemini found this.


-- I need to explain this
def statistical_distance' {D : Type*} [MeasurableSpace D] (X Y : ProbabilityMeasure D) := (2⁻¹) * (SignedMeasure.totalVariation (X.toMeasure.toSignedMeasure - Y.toMeasure.toSignedMeasure)) Set.univ
lemma statistical_distance_finite_1 {D : Type*} [MeasurableSpace D] (X Y : ProbabilityMeasure D)
  : IsFiniteMeasure ((X.toMeasure.toSignedMeasure - Y.toMeasure.toSignedMeasure).totalVariation) := isFiniteMeasureAdd
lemma statistical_distance_finite_2 {D : Type*} [MeasurableSpace D] (X Y : ProbabilityMeasure D)
  : statistical_distance' X Y < ∞ := by
    unfold statistical_distance'
    refine ENNReal.mul_lt_top ?_ ?_
    simp only [ENNReal.inv_lt_top, Nat.ofNat_pos]
    simp only [statistical_distance_finite_1, measure_lt_top]
def statistical_distance {D : Type*} [MeasurableSpace D] (X Y : ProbabilityMeasure D) : ℝ≥0 := statistical_distance' X Y |>.toNNReal

instance : Norm ℝ≥0 := ⟨(↑)⟩


def statistically_close {D : (n : ℕ) →  Type*} [∀n, MeasurableSpace (D n)] (X Y : (n : ℕ) → ProbabilityMeasure (D n)) :=
  negligible (fun n ↦ statistical_distance (X n) (Y n))


-- theorem lemma_5_1 {m : ℝ≥0} {_ : 2 * n }

-- #check Mathlib.Testing.SlimCheck

def mHyp (m n q : ℕ) : Prop := (2 * n * Real.log q) ≤ m

def sqrt_log : ℕ → ℝ := (Real.sqrt ∘  Real.log ∘ (↑))
def ω_sqrt_log (ω : ℕ → ℝ≥0) : Prop := ω =ω[Filter.atTop] sqrt_log


-- #check ZMod 2
-- def mod_q ( q : ℕ) := ℤ ⧸ (AddSubgroup.closure {(q : ℤ)})
-- lemma mod_q.isFinite {q : ℕ} : Finite (ZMod q) := by
--   apply?
--   sorry

-- seems like Fin q is the integers mod q
#eval (7 : Fin 6)
-- ZMod q is Fin q if q is positive

-- abbrev mod_q ( q : ℕ) := ZMod q

-- again, does Λ vary over n?
theorem Lemma_2_6_then
  (ω : (n : ℕ) → ℝ≥0) (hω : ω_sqrt_log ω)
  : ∃(ε : (n : ℕ) → ℝ≥0) (negl_ε : negligible ε) (ε_pos : ∀i, ε i ≠ 0), ∀i,
  smoothing_parameter Λ (ε_pos i) ≤ ω i / minimum_distance_sup (dualLattice Λ)
  := sorry
theorem Lemma_2_6_then'
  {ι : (n : ℕ) → Type*} [∀n, Fintype (ι n)] (Λ : (n : ℕ) → Submodule ℤ ((ι n) → ℝ)) [∀n, DiscreteTopology ↥(Λ n)] [∀n, IsZLattice ℝ (Λ n)]
  (ω : (n : ℕ) → ℝ≥0) (hω : ω_sqrt_log ω)
  : ∃(ε : (n : ℕ) → ℝ≥0) (negl_ε : negligible ε) (ε_pos : ∀n, ε n ≠ 0), ∀n,
  smoothing_parameter (Λ n) (ε_pos n) ≤ ω n / minimum_distance_sup (dualLattice (Λ n))
  := by
    have other n := Lemma_2_6_then (Λ n) ω hω
    have t n := other n |>.choose n
    use t

    sorry

-- note: NeZero allows this to be inferred, while h : q > 0 doesn't
example  {q : ℕ} [NeZero q] : Finite (ZMod q) := inferInstance

-- instance {q : ℕ} : Zero (ZMod q) where zero := 0

def A_Matrix (n m q : ℕ) : Type := Matrix (Fin n) (Fin m) (ZMod q)

instance A_Matrix.instFinite {n m q : ℕ} [NeZero q] : Finite (A_Matrix n m q) := Matrix.instFinite (ZMod q)
instance {n m q : ℕ} [NeZero q] : Nonempty (A_Matrix n m q) := Equiv.nonempty Matrix.of.symm

-- set_option trace.Meta.synthInstance true in
example (q)  [NeZero q] : Algebra ℤ (ZMod q) := inferInstance

def toZModLin (q) : ℤ →ₗ[ℤ] (ZMod q) := Algebra.linearMap ℤ (ZMod q)

#eval
  (List.range 10).map ((↑) : _ → ℤ) |>.map (toZModLin 3)

def A_Matrix.syndrome_map {n m q : ℕ} (A : A_Matrix n m q) : (Fin m → ℤ) →ₗ[ℤ] (Fin n → ZMod q) := by
  -- have := Matrix.toLin (m := Fin n) (n := Fin m) (R := ZMod q) sorry sorry
  let vl:= Matrix.mulVecLin A
  -- have this be →ₗ[ℤ] as well
  -- is converting to ZMod q the same before or after "this"?
  let : (Fin m → ℤ) →ₗ[ℤ] (Fin m → ZMod q) := by
    exact (toZModLin q).compLeft (Fin m)
  exact Fintype.linearCombination ℤ fun a a_1 ↦ A a_1 a

  -- refine ((LinearMap.comp this vl) )


-- this shows that modulo can be done before or after
example (q : ℕ) (a b : ℤ) : ((a : ZMod q) * (b : ZMod q)) = ↑(a * b) := by
  simp only [Int.cast_mul]

def A_Matrix.syndrome_map' {n m q : ℕ} (A : A_Matrix n m q) : (Fin m → ℤ) → (Fin n → ZMod q) := by
  intro x
  apply A.mulVec <| Int.cast ∘ x

section testing
open Plausible



instance {q} : Arbitrary (ZMod q) :=
  match q with
    | 0 => Int.Arbitrary
    | _ + 1 => Fin.Arbitrary
instance {q} : Shrinkable (ZMod q) :=
  match q with
    | 0 => Int.shrinkable
    | _ + 1 => Fin.shrinkable
#test ∀i : (ZMod 5), i + 0 = i
#test ∀i : (Fin 2 → Fin 2), i + 0 = i

-- experimentally checks that syndrome_map is correct
#eval Testable.check
    (∀ ee : _ → _ → (ZMod _),
    let A : A_Matrix 3 4 5 := Matrix.of ee;
    ∀xx, A.syndrome_map xx = A.syndrome_map' xx)
  {traceSuccesses := true}



end testing

#check DiscreteMeasurableSpace
-- #check OpensMeasurableSpace

instance A_Matrix.instMeasurableSpace (n m q : ℕ) [NeZero q] : MeasurableSpace (A_Matrix n m q) := ⊤
example (n m q : ℕ) [NeZero q] : DiscreteMeasurableSpace (A_Matrix n m q) := inferInstance

def A_Matrix.uniform {n m q : ℕ} [NeZero q] : ProbabilityMeasure (A_Matrix n m q) :=
  ⟨ProbabilityTheory.uniformOn Set.univ,
  ProbabilityTheory.uniformOn_isProbabilityMeasure Set.finite_univ Set.univ_nonempty⟩

instance {n m q : ℕ} [NeZero q] : MeasureSpace (A_Matrix n m q) where
  volume := @A_Matrix.uniform n m q _


def uniform_over_Zqn (n q : ℕ) [NeZero q] : ProbabilityMeasure (Fin n → ZMod q) :=
  ⟨ProbabilityTheory.uniformOn Set.univ,
  ProbabilityTheory.uniformOn_isProbabilityMeasure Set.finite_univ Set.univ_nonempty⟩

#check ProbabilityTheory.uniformOn_univ


#check int_gaussian


-- "the subset-sums of the columns of A generate Zqn"
def lemma_5_1_statement {n m q : ℕ} (A : A_Matrix n m q) : Prop :=
  A.syndrome_map '' {e | ∀i, e i = 0 ∨ e i = 1} = Set.univ

-- the form seems complete
-- wait, is q_prime
theorem lemma_5_1 {n m q : ℕ} [NeZero q]  (q_prime : Nat.Prime q) (m_hyp : mHyp m n q) : ℙ (lemma_5_1_statementᶜ : Set <| A_Matrix n m q) ≤ (q ^ (- n : ℝ)) := sorry

-- {e | Ae mod q = 0 }
def A_Matrix.Λ_ortho {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) : AddSubgroup (Fin m → ℤ) := A.syndrome_map.toAddMonoidHom.ker

-- does it matter that this is ZMod q?
-- I wonder, a philosophical idea about a sense in which ℕ is equivalent to {0 mod 2, 1 mod 2}
def A_Matrix.Λ_main_base {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) : AddSubgroup (Fin m → ZMod q) := (A_Matrix.syndrome_map (A.transpose : A_Matrix m n q)).toAddMonoidHom.range
def A_Matrix.Λ_main {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) : AddSubgroup (Fin m → ℤ)
  := (A_Matrix.syndrome_map A.transpose).toAddMonoidHom.range.comap
  ((Int.castAddHom (ZMod q)).compLeft (Fin m))

def to_R {m} (L : AddSubgroup (Fin m → ℤ) ) : Submodule ℤ (Fin m → ℝ) := (AddSubgroup.map ((Int.castAddHom ℝ).compLeft (Fin m)) L).toIntSubmodule

def A_Matrix.Λ_ortho' {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) : Submodule ℤ (Fin m → ℝ) := to_R A.Λ_ortho
def A_Matrix.Λ_main' {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) : Submodule ℤ (Fin m → ℝ) := to_R A.Λ_main

theorem A_Matrix.Λ_dual {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) :
  -- (to_R A.Λ_ortho) = (q : ℤ) • (dualLattice <| to_R A.Λ_main)
  (A.Λ_ortho') = (dualLattice <| A.Λ_main').map (LinearMap.lsmul ℤ _ q)
  := by sorry
theorem A_Matrix.Λ_dual' {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) :
  (A.Λ_main') = (dualLattice <| A.Λ_ortho').map (LinearMap.lsmul ℤ _ q)
  := by sorry

lemma A_Matrix.Λ_ortho'.has_qZn {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) :
  ∀i, Pi.single i q ∈ (A.Λ_ortho') := by
    intro i
    refine (Submodule.mem_toAddSubgroup A.Λ_ortho').mp ?_
    unfold Λ_ortho' to_R
    simp only [AddSubgroup.toIntSubmodule_toAddSubgroup, AddSubgroup.mem_map]
    unfold Λ_ortho
    simp only [AddMonoidHom.mem_ker, LinearMap.toAddMonoidHom_coe]
    use Pi.single i q
    constructor
    {
      ext j
      unfold syndrome_map
      simp only [Fintype.linearCombination_apply_single, Pi.smul_apply, zsmul_eq_mul,
        Int.cast_natCast, CharP.cast_eq_zero, zero_mul, Pi.zero_apply]
    }
    ext j
    simp only [AddMonoidHom.compLeft_apply, Int.coe_castAddHom, Function.comp_apply]
    by_cases h : i = j
    subst h
    simp only [Pi.single_eq_same, Int.cast_natCast]
    simp only [ne_eq, h, not_false_eq_true, Pi.single_eq_of_ne', Int.cast_zero]





#check instIsZLatticeComap
#check Submodule.IsLattice

instance A_Matrix.Λ_ortho'.instDiscreteTopology {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) :
  DiscreteTopology ↥(A.Λ_ortho') := sorry
instance A_Matrix.Λ_ortho'.instIsZLattice {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) :
  IsZLattice ℝ (A.Λ_ortho') := sorry
instance A_Matrix.Λ_main'.instDiscreteTopology {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) :
  DiscreteTopology ↥(A.Λ_main') := sorry
instance A_Matrix.Λ_main'.instIsZLattice {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) :
  IsZLattice ℝ (A.Λ_main') := sorry

def A_Matrix.syndrome_distributed {n m q : ℕ} [NeZero q] (A : A_Matrix n m q)
  (e : ProbabilityMeasure (Fin m → ℤ))
  := e.map (f := A.syndrome_map) (AEMeasurable.of_discrete)

theorem lemma_5_2 {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) (ass : lemma_5_1_statement A)
  (ε : ℝ≥0) (ε_pos : ε ≠ 0) (ε_bound : ε < 2⁻¹) (s : ℝ≥0) [Fintype (Fin m)]
  (s_prop : s ≥ smoothing_parameter (A.Λ_ortho') ε_pos) :
  let hs : s ≠ 0 := sorry;
  statistical_distance (A.syndrome_distributed (int_gaussian m hs)) (uniform_over_Zqn _ _) ≤ 2 * ε
  := sorry

theorem lemma_5_2_furthermore {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) (ass : lemma_5_1_statement A)
  (ε : ℝ≥0) (ε_pos : ε ≠ 0) (ε_bound : ε < 2⁻¹) (s : ℝ≥0) [Fintype (Fin m)]
  (s_prop : s ≥ smoothing_parameter (A.Λ_ortho') ε_pos) (u : Fin n → ZMod q) (t : Fin m → ℤ) (ht : A.syndrome_map t = u)
  :
  let hs : s ≠ 0 := sorry;
  -- ProbabilityTheory.cond (int_gaussian m hs) (A.syndrome_map ⁻¹' {u}) = t +ᵥ (int_gaussian_sublattice m hs A.Λ_ortho (-t))
  ProbabilityTheory.cond (int_gaussian m hs) (A.syndrome_map ⁻¹' {u}) = (int_gaussian_sublattice m hs A.Λ_ortho (-t)).map (f := (· + t)) (AEMeasurable.of_discrete)
  := sorry


def lemma_5_3_statement {n m q : ℕ} [NeZero q] (A : A_Matrix n m q) : Prop :=
  minimum_distance_sup (A.Λ_main') ≥ q/4

abbrev N := ℕ
abbrev M := ℕ
abbrev Q := ℕ

def mHyp' (m : N → M) (q : N → Q) : Prop := ∀n, (2 * n * Real.log (q n)) ≤ m n

lemma mHyp'_linear (m : N → M) (q : N → Q) (q_prime : ∀n, Nat.Prime (q n)) (m_hyp : mHyp' m q) : id ≤ m :=
  by
  unfold mHyp' at m_hyp
  intro n
  dsimp only [id_eq]
  specialize m_hyp n
  rify
  apply le_trans ?_ m_hyp
  have t n : 2 ≤ (q n : ℝ) := by
    simp only [Nat.ofNat_le_cast]
    apply Nat.Prime.two_le (q_prime n)
  have tt : Real.log (2) ≤ Real.log ↑(q n) := by
    apply Real.log_le_log zero_lt_two
    exact t n

  trans  ↑n * 2 * Real.log 2
  sorry
  ring_nf
  refine mul_le_mul ?_ (by rfl) zero_le_two (by positivity)
  refine mul_le_mul (by rfl) tt (by positivity) (Nat.cast_nonneg' n)

lemma mHyp'_tendsTo (m : N → M) (q : N → Q) (q_prime : ∀n, Nat.Prime (q n)) (m_hyp : mHyp' m q) : Filter.Tendsto m Filter.atTop Filter.atTop := sorry

theorem lemma_5_3       {n m q : ℕ} [NeZero q] (q_prime : Nat.Prime q) (m_hyp : mHyp m n q)
  : ℙ (lemma_5_3_statementᶜ : Set <| A_Matrix n m q) ≤ (q ^ (- n : ℝ)) := sorry


theorem lemma_5_3_also (q : N → Q) [∀n, NeZero (q n)]  (m : N → M) (q_prime : ∀n, Nat.Prime (q n)) (m_hyp : mHyp' m q)
  (A : (n : N) → (A_Matrix n (m n) (q n)))(hA : ∀n, lemma_5_3_statement (A n))
  (ω : (m : M) → ℝ≥0) (hω : ω_sqrt_log ω)
  : ∃ (ε : (m : M) → ℝ≥0) (negl_ε : negligible ε) (ε_pos : ∀m, ε m ≠ 0),
  ∀n : N, smoothing_parameter ((A n).Λ_ortho') (ε_pos (m n)) ≤ ω (m n) := by

  #check Lemma_2_6_then'
  #check A_Matrix.Λ_dual'
  have ⟨ε, negl_ε, ε_pos, so⟩:= Lemma_2_6_then' (fun n ↦ (A n).Λ_ortho') (ω ∘ m) ?_
  use ε, negl_ε, ε_pos
  intro n
  specialize so n
  specialize hA n
  unfold lemma_5_3_statement at hA
  nth_rw 2 [A_Matrix.Λ_dual] at so





  sorry
  have m_top := mHyp'_tendsTo _ _ q_prime m_hyp
  #check IsLittleO.comp_tendsto
  unfold ω_sqrt_log at *
  #check IsBigO.trans_isLittleO
  have : (ω) =O[Filter.atTop] (ω ∘ m) := by sorry
  -- refine IsBigO.trans_isLittleO ?_ ?_

  sorry


-- hmm, in Corollary 5.4, "statistically close" describes what happens as n varies, but A is conditioned on n. this means statistically_close does not fit
-- what does it mean?

-- the distribution of the syndrome is statistically close to uniform
-- statistically close = statistical distance is negligible in n
-- blackboard: (A, Ax mod q) ≈ (A, y)     f m ≥ ...
-- is it expressed that the distribution sampled from (A : Uniform,e : Gaussian) to (A, Ae mod q), is compared to the distribution (A : Uniform, y: Uniform),
--  and these distributions have type [ProbabilityMeasure ()]
#check let n :=5; let m := 7; let q := 10;
  ProbabilityMeasure ((A_Matrix n m q) × (Fin n → ZMod q))




-- example (q : ℕ → ℕ) (m : ℕ → ℕ)

-- this collection of subsets have all but 2q^-n values
def corollary_5_4_condition {q : N → Q} [∀n, NeZero (q n)] {m : N → M} (subsets : (n : N) → Set (A_Matrix n (m n) (q n)))
  := (∀n, ℙ (subsets n) ≤ 2 * ((q n) ^ (- n : ℝ)))


def corollary_5_4_statement (q : N → Q) [∀n, NeZero (q n)]  (m : N → M)
  (A : (n : N) → A_Matrix n (m n) (q n)) (s : N → ℝ≥0) (s_pos : ∀n, s n ≠ 0) :=
    statistically_close
      (fun n ↦ (A n).syndrome_distributed (int_gaussian (m n) (s_pos n)))
      (fun n ↦ uniform_over_Zqn n (q n))


theorem corollary_5_4 (q : N → Q) [∀n, NeZero (q n)]  (m : N → M) (q_hyp : ∀n, Nat.Prime (q n)) (m_hyp : mHyp' m q)
  : ∃(subsets : (n : N) → Set (A_Matrix n (m n) (q n)))(_ : corollary_5_4_condition subsets),
  ∀(s : N → ℝ≥0)(_ : s =ω[Filter.atTop] (sqrt_log ∘ m))(s_pos : ∀n, s n ≠ 0), -- ≥ω is the same as =ω, right?
  ∀(A : (n : N) → (A_Matrix n (m n) (q n)))(_ : ∀n, A n ∈ subsets n),
  corollary_5_4_statement q m A s s_pos
  := by


  sorry

-- should s be a function of m?

-- idea: have m be N → M, to not confuse variables

-- unrelated idea: Module with polynomials as the scalars.
